services:
  redis:
    image: "redis:4.0.11-alpine"
  www:
    build:
      context: .
    ports:
      - "3000:80"
    command: nodemon bin/www.js
    volumes:
      - .:/src
    environment:
      - REDIS_URL=redis://redis:6379
